name: Code Quality

on:
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - 'copilot/**'
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  quality:
    uses: frasermolyneux/actions/.github/workflows/codequality.yml@main
    with:
      sonar-project-key: frasermolyneux_travel-itinerary
      sonar-organization: frasermolyneux
      sonar-host-url: https://sonarcloud.io
      build-target: dotnet-web-ci
      dotnet-project: MX.TravelItinerary.Web
      dotnet-version: 9.0.x
      src-folder: src
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
