name: Deploy Prd

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 4"

permissions: {}

concurrency:
  group: ${{ github.workflow }}

jobs:
  detect-changes:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
      terraform: ${{ steps.changes.outputs.terraform }}
    steps:
      - id: changes
        uses: frasermolyneux/actions/detect-changes@main
        with:
          filters: |
            src:src/**
            terraform:terraform/**

  build-and-test:
    needs:
      - detect-changes
    if: needs.detect-changes.outputs.src == 'true'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: frasermolyneux/actions/dotnet-web-ci@dotnet-web-ci/v1.4
        with:
          dotnet-project: "MX.TravelItinerary.Web"
          dotnet-version: 9.0.x
          src-folder: "src"
          skip-nuget-artifact-upload: "true"

  terraform-plan-and-apply-dev:
    permissions:
      contents: read
      id-token: write
    environment: Development
    needs:
      - detect-changes
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-dev
    steps:
      - id: state-check-dev
        uses: frasermolyneux/actions/terraform-state-check@terraform-state-check/v1.0
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/dev.tfvars"
          terraform-backend-file: "backends/dev.backend.hcl"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - if: needs.detect-changes.outputs.terraform == 'true' || steps.state-check-dev.outputs.has_resources != 'true'
        uses: frasermolyneux/actions/terraform-plan-and-apply@terraform-plan-and-apply/v1.4
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/dev.tfvars"
          terraform-backend-file: "backends/dev.backend.hcl"
          perform-checkout: "false"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - if: needs.detect-changes.outputs.terraform != 'true' && steps.state-check-dev.outputs.has_resources == 'true'
        uses: frasermolyneux/actions/terraform-output@terraform-output/v1.0
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/dev.tfvars"
          terraform-backend-file: "backends/dev.backend.hcl"
          perform-checkout: "false"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - id: terraform-output-dev
        shell: bash
        run: |
          cd terraform
          echo "web_app_resource_group_name=$(terraform output -raw web_app_resource_group_name)" >> $GITHUB_OUTPUT
          echo "web_app_name=$(terraform output -raw web_app_name)" >> $GITHUB_OUTPUT
        env:
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_USE_AZUREAD: true
          ARM_USE_OIDC: true

    outputs:
      web_app_resource_group_name: ${{ steps.terraform-output-dev.outputs.web_app_resource_group_name }}
      web_app_name: ${{ steps.terraform-output-dev.outputs.web_app_name }}

  app-service-deploy-dev:
    if: |
      !failure() && !cancelled() && needs.detect-changes.outputs.src == 'true'
    permissions:
      contents: read
      id-token: write
    environment: Development
    needs:
      - detect-changes
      - build-and-test
      - terraform-plan-and-apply-dev
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-dev
    steps:
      - uses: frasermolyneux/actions/deploy-app-service@deploy-app-service/v1.2
        with:
          web-artifact-name: "MX.TravelItinerary.Web"
          web-app-name: ${{ needs.terraform-plan-and-apply-dev.outputs.web_app_name }}
          resource-group-name: ${{ needs.terraform-plan-and-apply-dev.outputs.web_app_resource_group_name }}
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

  terraform-plan-and-apply-prd:
    if: |
      !failure() && !cancelled() && needs.terraform-plan-and-apply-dev.result == 'success'
    permissions:
      contents: read
      id-token: write
    environment: Production
    needs:
      - detect-changes
      - build-and-test
      - terraform-plan-and-apply-dev
      - app-service-deploy-dev
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-prd
    steps:
      - id: state-check-prd
        uses: frasermolyneux/actions/terraform-state-check@terraform-state-check/v1.0
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/prd.tfvars"
          terraform-backend-file: "backends/prd.backend.hcl"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - if: needs.detect-changes.outputs.terraform == 'true' || steps.state-check-prd.outputs.has_resources != 'true'
        uses: frasermolyneux/actions/terraform-plan-and-apply@terraform-plan-and-apply/v1.4
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/prd.tfvars"
          terraform-backend-file: "backends/prd.backend.hcl"
          perform-checkout: "false"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - if: needs.detect-changes.outputs.terraform != 'true' && steps.state-check-prd.outputs.has_resources == 'true'
        uses: frasermolyneux/actions/terraform-output@terraform-output/v1.0
        with:
          terraform-folder: "terraform"
          terraform-var-file: "tfvars/prd.tfvars"
          terraform-backend-file: "backends/prd.backend.hcl"
          perform-checkout: "false"
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - id: terraform-output-prd
        shell: bash
        run: |
          cd terraform
          echo "web_app_resource_group_name=$(terraform output -raw web_app_resource_group_name)" >> $GITHUB_OUTPUT
          echo "web_app_name=$(terraform output -raw web_app_name)" >> $GITHUB_OUTPUT
        env:
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_USE_AZUREAD: true
          ARM_USE_OIDC: true

    outputs:
      web_app_resource_group_name: ${{ steps.terraform-output-prd.outputs.web_app_resource_group_name }}
      web_app_name: ${{ steps.terraform-output-prd.outputs.web_app_name }}

  app-service-deploy-prd:
    if: |
      !failure() && !cancelled() && needs.terraform-plan-and-apply-prd.result == 'success' && needs.detect-changes.outputs.src == 'true'
    permissions:
      contents: read
      id-token: write
    environment: Production
    needs:
      - detect-changes
      - build-and-test
      - terraform-plan-and-apply-prd
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-prd
    steps:
      - uses: frasermolyneux/actions/deploy-app-service@deploy-app-service/v1.2
        with:
          web-artifact-name: "MX.TravelItinerary.Web"
          web-app-name: ${{ needs.terraform-plan-and-apply-prd.outputs.web_app_name }}
          resource-group-name: ${{ needs.terraform-plan-and-apply-prd.outputs.web_app_resource_group_name }}
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
